[phases.setup]
nixPkgs = ['nodejs_18']
workDir = '/app/backend'

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = ['echo "No build step required for backend"']

[start]
cmd = 'cd backend && npm start'